name: Test Secrets

on:
  push:
    branches:
      - main

jobs:
  test-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Display Secret
        run: echo "SECRET_VAR=${{ secrets.SECRET_VAR }}"

      - name: Check if secret exists
        run: |
          if [ -z "${{ secrets.SECRET_VAR }}" ]; then
            echo "SECRET_VAR is empty"
            exit 1
          else
            echo "SECRET_VAR is set"
          fi
